FROM node:18.20.4

RUN node --version
RUN apk add --update --no-cache curl jq py3-configobj py3-pip py3-setuptools python3 python3-dev

RUN apk update && \
    apk add --no-cache git python3 build-base && \
    mkdir -p /home/node/app

WORKDIR /home/node/app/website

ARG DATA_API_BASE_URL
ENV DATA_API_BASE_URL $DATA_API_BASE_URL

ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH $GIT_COMMIT_HASH

CMD yarn && (yarn start --host 0.0.0.0 & yarn start:export --host website)
